invite-github.webp:
	ffmpeg -framerate 1/2 -loop 0 -pattern_type glob -i 'screenshots/invite-github/*.png' invite-github.webp

invite-gitlab.webp:
	ffmpeg -framerate 1/2 -loop 0 -pattern_type glob -i 'screenshots/invite-gitlab/*.png' invite-gitlab.webp
